### ISSUE TITLE
Apple Silicon laptops fails to check for Battery status on Download Upgrade Reinstall Erase script 

### ISSUE THREAD

**Issue by macbm** [kdrwygvh/Sunstein_macOSUpdates#1]
Seems the function checkBatteryStatus fails on Apple Silicon laptops, so user is never prompted to connect to power source.

Error log shows:

> + currentPowerDrawStatus='Now drawing from '\''Battery Power'\'''
> + [[ Now drawing from 'Battery Power' =~ Now drawing from 'Battery Power' ]]
> ++ ioreg -r -c AppleSmartBattery
> ++ grep -w MaxCapacity
> ++ awk '{print $3}'
> ++ sed 's/"//g'
> + BatteryMaximumCapacity='{Ra03=0,Ra10=0,CellWom=(0,0),RaTableRaw=(<00000062005000550066007600590065005e00650069006f008500c801a0029a>,<00550060004e005100640077005d0066005f0068006d0072008400cc01b102bc>,<005500760062006700760089006f007d00730079007f0085009b00dd01b702b7>),Qstart=0,AdapterPower=968956716,DailyMinSoc=44,Ra04=0,Ra11=0,CellVoltage=(3801,3800,3799),PackCurrentAccumulator=18446744073709319953,PassedCharge=158,Flags=16777217,PresentDOD=(55,55,55),Ra05=0,Ra12=0,FccComp1=4306,ChemID=10037,iMaxAndSocSmoothTable=<0000000000000000000000000000000000000000000000000000000000000000>,FccComp2=4306,PackCurrentAccumulatorCount=642,DOD0=(8448,8448,8448),Ra06=0,ResScale=0,Ra13=0,WeightedRa=0,FilteredCurrent=0,RSS=0,CellCurrentAccumulatorCount=0,Serial=D860514AEM0PZADV7,DataFlashWriteCount=1513,DailyMaxSoc=44,Ra07=0,Ra14=0,MaxCapacity=100,ChemicalWeightedRa=0,Ra00=0,BatteryHealthMetric=0,DesignCapacity=4382,Ra08=0,BatteryState=<000000000000000043e40002c5000002>,CellCurrentAccumulator=(0,0),AlgoChemID=10037,MfgData=<00000000100200012735000003313731033030320341544c003a000000000000>,ManufactureDate=59584923383858,ISS=18446744073709551362,Ra01=0,Soc1Voltage=0,QmaxDisqualificationReason=0,ChargeAccum=0,SimRate=0,Qmax=(4559,4547,4551),PMUConfigured=0,ITMiscStatus=0,StateOfCharge=43,Ra09=0,GaugeFlagRaw=192,CycleCount=15,Voltage=11400,SystemPower=1077549723,LifetimeData={Raw=<000039c70009472d00002f0d00000000010f2e730000e447b24000000000000001d6004311000e3132f02aac0e14f609114ef49ef9b5f8f400c90001348c0004>,UpdateTime=1625789418,ResistanceUpdatedDisabledCount=0,CycleCountLastQmax=11,TimeAtHighSoc=<04000000a80000000300000000000000>,TemperatureSamples=78988,TotalOperatingTime=4936,MaximumDischargeCurrent=18446744073709549065,MinimumPackVoltage=10924,MaximumPackVoltage=13040,MaximumChargeCurrent=3604,AverageTemperature=18446744073709551561,MinimumTemperature=67,RDISCnt=0,MaximumTemperature=470},Ra02=0}
> 100'
> ++ ioreg -r -c AppleSmartBattery
> ++ grep -w CurrentCapacity
> ++ sed 's/"//g'
> ++ awk '{print $3}'
> + BatteryCurrentCapacity=44
> ++ echo 'scale=4; (44 / {Ra03=0,Ra10=0,CellWom=(0,0),RaTableRaw=(<00000062005000550066007600590065005e00650069006f008500c801a0029a>,<00550060004e005100640077005d0066005f0068006d0072008400cc01b102bc>,<005500760062006700760089006f007d00730079007f0085009b00dd01b702b7>),Qstart=0,AdapterPower=968956716,DailyMinSoc=44,Ra04=0,Ra11=0,CellVoltage=(3801,3800,3799),PackCurrentAccumulator=18446744073709319953,PassedCharge=158,Flags=16777217,PresentDOD=(55,55,55),Ra05=0,Ra12=0,FccComp1=4306,ChemID=10037,iMaxAndSocSmoothTable=<0000000000000000000000000000000000000000000000000000000000000000>,FccComp2=4306,PackCurrentAccumulatorCount=642,DOD0=(8448,8448,8448),Ra06=0,ResScale=0,Ra13=0,WeightedRa=0,FilteredCurrent=0,RSS=0,CellCurrentAccumulatorCount=0,Serial=D860514AEM0PZADV7,DataFlashWriteCount=1513,DailyMaxSoc=44,Ra07=0,Ra14=0,MaxCapacity=100,ChemicalWeightedRa=0,Ra00=0,BatteryHealthMetric=0,DesignCapacity=4382,Ra08=0,BatteryState=<000000000000000043e40002c5000002>,CellCurrentAccumulator=(0,0),AlgoChemID=10037,MfgData=<00000000100200012735000003313731033030320341544c003a000000000000>,ManufactureDate=59584923383858,ISS=18446744073709551362,Ra01=0,Soc1Voltage=0,QmaxDisqualificationReason=0,ChargeAccum=0,SimRate=0,Qmax=(4559,4547,4551),PMUConfigured=0,ITMiscStatus=0,StateOfCharge=43,Ra09=0,GaugeFlagRaw=192,CycleCount=15,Voltage=11400,SystemPower=1077549723,LifetimeData={Raw=<000039c70009472d00002f0d00000000010f2e730000e447b24000000000000001d6004311000e3132f02aac0e14f609114ef49ef9b5f8f400c90001348c0004>,UpdateTime=1625789418,ResistanceUpdatedDisabledCount=0,CycleCountLastQmax=11,TimeAtHighSoc=<04000000a80000000300000000000000>,TemperatureSamples=78988,TotalOperatingTime=4936,MaximumDischargeCurrent=18446744073709549065,MinimumPackVoltage=10924,MaximumPackVoltage=13040,MaximumChargeCurrent=3604,AverageTemperature=18446744073709551561,MinimumTemperature=67,RDISCnt=0,MaximumTemperature=470},Ra02=0}
> 100) * 100'
> ++ bc
> ++ awk -F . '{print $1}'
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: W
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: illegal character: T
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: Q
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: P
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: M
> (standard_in) 1: illegal character: S
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: V
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: P
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: P
> (standard_in) 1: parse error
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: P
> (standard_in) 1: illegal character: O
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: I
> (standard_in) 1: illegal character: M
> (standard_in) 1: illegal character: S
> (standard_in) 1: illegal character: S
> (standard_in) 1: illegal character: T
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: P
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: O
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: illegal character: S
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: W
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: illegal character: S
> (standard_in) 1: illegal character: S
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: S
> (standard_in) 1: illegal character: M
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: P
> (standard_in) 1: illegal character: J
> (standard_in) 1: illegal character: Y
> (standard_in) 1: illegal character: R
> (standard_in) 1: illegal character: W
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: M
> (standard_in) 1: illegal character: S
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: M
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: W
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: H
> (standard_in) 1: illegal character: M
> (standard_in) 1: parse error
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: S
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: I
> (standard_in) 1: illegal character: M
> (standard_in) 1: illegal character: M
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: I
> (standard_in) 1: illegal character: S
> (standard_in) 1: illegal character: S
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: S
> (standard_in) 1: illegal character: V
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: Q
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: S
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: Q
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: P
> (standard_in) 1: illegal character: M
> (standard_in) 1: illegal character: U
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: I
> (standard_in) 1: illegal character: T
> (standard_in) 1: illegal character: M
> (standard_in) 1: illegal character: S
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: S
> (standard_in) 1: illegal character: O
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: G
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: V
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: S
> (standard_in) 1: illegal character: P
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: L
> (standard_in) 1: illegal character: R
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: U
> (standard_in) 1: illegal character: T
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: illegal character: U
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: L
> (standard_in) 1: illegal character: Q
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: T
> (standard_in) 1: illegal character: H
> (standard_in) 1: illegal character: S
> (standard_in) 1: illegal character: T
> (standard_in) 1: illegal character: S
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: T
> (standard_in) 1: illegal character: O
> (standard_in) 1: illegal character: T
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: M
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: M
> (standard_in) 1: illegal character: P
> (standard_in) 1: illegal character: V
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: M
> (standard_in) 1: illegal character: P
> (standard_in) 1: illegal character: V
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: M
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: T
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: M
> (standard_in) 1: illegal character: T
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 1: illegal character: I
> (standard_in) 1: illegal character: S
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: M
> (standard_in) 1: illegal character: T
> (standard_in) 1: parse error
> (standard_in) 1: illegal character: R
> (standard_in) 2: parse error
> + BatteryPercentage=
> + '[' '' -lt 50 ']'
> /Library/Application Support/JAMF/tmp/macOS-Download Upgrade Reinstall Erase-7.2021.sh: line 281: [: : integer expression expected
> + echo 'Battery level currently at , proceeding'
> Battery level currently at , proceeding
> + checkAvailableDiskSpace

**Comment by kdrwygvh** [comment]
Thank you. I  have fixed this in the development branch. Let me know how it goes.

**Comment by kdrwygvh** [comment]
Issue resolved by improving searches on battery capacity and current charge
